name: RS Email Scraper Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Mengizinkan tombol 'Run workflow' secara manual di GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        npm ci
        npx playwright install-deps
        npx playwright install

    - name: Run Scraper Script
      run: node scraper.js

    - name: Upload Excel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: data-excel-rs
        path: Hasil_Scraping_RS.xlsx
